project/accounts/urls.py
from django.urls import path, include
from . import views


app_name = 'accounts'

urlpatterns = [
    path('profile/', views.UserProfile, name="user-profile"),
    path('profile/<str:slug>', views.profile, name="profile"),
    path('addfriend/<str:slug>', views.addfriend, name="addfriend"),
    path('', include('django.contrib.auth.urls')),
]

project/games/urls.py
from django.urls import path
from . import views

app_name = 'games'

urlpatterns = [
    path('', views.index, name='index'),
    path('details/<str:slug>/', views.details, name='details'),
    path('browse/', views.browse, name='browse'),
    path('search/', views.search, name='search')
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('', include('games.urls', namespace='games')),
    path('streams/', include('streams.urls', namespace='streams')),
]

# Media
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

project/streams/urls.py
from django.urls import path
from . import views

app_name = 'streams'

urlpatterns = [
    path('', views.streams, name='streams')
]

project/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User,related_name="profile", on_delete=models.CASCADE, verbose_name='user')
    bio = models.TextField(max_length = 90, blank=True, null=True)
    image = models.FileField(upload_to="Accounts/users/profiles-images/%d/",blank=True, null=True)
    friends = models.ManyToManyField(User, blank=True, related_name="friends")
    
    slug = models.SlugField(blank=True, null=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.user.username)
        super(Profile, self).save(*args, **kwargs) # Call the real save() method

    def __str__(self):
        return self.user.username
    

project/games/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
# Create your models here.

class Type(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name



class Game(models.Model):
    name = models.CharField(max_length=50)
    gamefile = models.FileField(upload_to="Games/%d/",blank=True, null=True)
    video = models.URLField(max_length=255, blank=True, null=True)
    company = models.CharField(max_length=50)
    mimage = models.FileField(upload_to="Games/main-images/%d/",blank=True, null=True)
    downloaders = models.ManyToManyField(User, related_name='games', blank=True)
    rate = models.DecimalField(max_digits=2, decimal_places=1, blank=True)
    type = models.ForeignKey(Type, on_delete=models.PROTECT, blank=True, null=True)
    storage = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    discription = models.TextField(max_length=300, default="An Amazing Game")
    data_added = models.DateField(auto_created=True, blank=True, null=True)
    slug = models.SlugField(null=True, blank=True)

    def save(self, *args, **kwargs):
       self.slug = slugify(self.name)
       super(Game, self).save(*args, **kwargs) # Call the real save() method

    def __str__(self):
        return self.name


class Image(models.Model):
    image = models.FileField(upload_to="Images/%d/",blank=True, null=True)
    game = models.ForeignKey(Game, on_delete=models.CASCADE, related_name='images')
    def __str__(self):
        return self.game.name

project/streams/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Type(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Stream(models.Model):
    title = models.CharField(max_length=50)
    streamer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='streams')
    game = models.OneToOneField("games.Game", on_delete=models.CASCADE, related_name='streams')
    image = models.FileField(upload_to="Streams/images/%d/",blank=True, null=True)
    type = models.ForeignKey(Type, on_delete=models.CASCADE)
    stream_url = models.URLField(max_length=255, blank=True, null=True)
    viewers = models.ManyToManyField(User, related_name='stream_viewer', blank=True)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.title

project/accounts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import *

# Create your views here.

def profile (request, slug):

    pro = get_object_or_404(Profile, slug = slug)

    context = {
        'profile': pro,
    }
    return render(request, 'pages/profile.html', context)

def UserProfile (request):

    pro = get_object_or_404(Profile, slug=request.user.profile.slug)

    context = {
        'profile': pro,
    }
    return render(request, 'pages/profile.html', context)


def addfriend(request, slug):
    print("done")
    friend = get_object_or_404(Profile, slug = slug)
    print(friend.user)
    if friend in request.user.friends.all:
        request.user.friends.remove(friend.user)
    else :
        request.user.friends.add(friend.user)
    print("done")
    return redirect('/')

project/games/views.py
from django.shortcuts import render, get_object_or_404
from .models import *
from streams.models import *
from accounts.models import *
# Create your views here.

def index(request):
    games = Game.objects.all()
    context = {
        'games': games,

    }
    return render(request, 'pages/index.html', context)


def details(request, slug):
    game = get_object_or_404(Game, slug = slug)
    games = Game.objects.all()
    context = {
        'game' : game,
        'games' : games,

    }
    return render(request, 'pages/details.html', context)


def browse(request):
    streams = Stream.objects.all()
    games = Game.objects.all()
    context = {
        'streams' : streams,
        'games' : games,
        
    }
    return render(request, 'pages/browse.html', context)


def search(request):
    name = None
    if 'searchKeyword' in request.GET:
        name = request.GET['searchKeyword']
        if name:
            games = Game.objects.filter(name__icontains = name)
            users = User.objects.filter(username__icontains = name)
            streams = Stream.objects.filter(title__icontains = name)
        else:
            games = Game.objects.all()
            users = User.objects.all()
            streams = Stream.objects.all()

    context = {
        'games' : games,
        'users' : users,
        'streams' : streams, 
    }
    return render(request, 'pages/search.html', context)

project/streams/views.py
from django.shortcuts import render
from .models import *
from games.models import *
from accounts.models import *
from django.contrib.auth.models import User
# Create your views here.

def streams(request):
    games = Game.objects.all()
    streams = Stream.objects.all()
    users = User.objects.all()
    context = {
        'streams' : streams,
        'games' : games,
        'streamers' : users
    }

    return render(request, 'pages/streams.html', context)

project/templates/pages/browse.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  


          <!-- ***** Featured Games Start ***** -->
          <div class="row">
            <div class="col-lg-8">
              <div class="featured-games header-text">
                <div class="heading-section">
                  <h4><em>Featured</em> Games</h4>
                </div>
                <div class="owl-features owl-carousel">
                  
                  {% for game in games %}
                    <div class="item">
                      <div class="thumb">
                        <img src="{{game.mimage.url}}" alt="">
                        <div class="hover-effect">
                          <h6>{{game.streams.count}} Streaming</h6>
                        </div>
                      </div>
                      <h4><a href="{% url 'games:details' game.slug %}">{{game.name}}</a><br><span>{{game.downloaders.count}} Downloads</span></h4>
                      <ul>
                        <li><i class="fa fa-star"></i> {{game.rate}}</li>
                        <li><i class="fa fa-download"></i> {{game.downloaders.count}}</li>
                      </ul>
                    </div>
                  {% endfor %}
                    
                </div>
              </div>
            </div>
            <div class="col-lg-4">
              <div class="top-downloaded">
                <div class="heading-section">
                  <h4><em>Top</em> Downloaded</h4>
                </div>
                <ul>
                  {% for game in games|slice:3 %}
                    <li>
                      <img src="{{game.mimage.url}}" alt="" class="templatemo-item">
                      <h4><a href="{% url 'games:details' game.slug %}">{{game.name}}</a></h4>
                      <h6>{{game.company}}</h6>
                      <span><i class="fa fa-star" style="color: yellow;"></i> {{game.rate}}</span>
                      <span><i class="fa fa-download" style="color: #ec6090;"></i> {{game.downloaders.count}}</span>
                      <div class="download">
                        <a href="#"><i class="fa fa-download"></i></a>
                      </div>
                    </li>
                  {% endfor %}
                </ul>
                <div class="text-button">
                  <a href="{% url 'games:browse' %}">View All Games</a>
                </div>
              </div>
            </div>
          </div>
          <!-- ***** Featured Games End ***** -->

          <!-- ***** Start Stream Start ***** -->
          <div class="start-stream">
            <div class="col-lg-12">
              <div class="heading-section">
                <h4><em>How To Start Your</em> Live Stream</h4>
              </div>
              <div class="row">
                <div class="col-lg-4">
                  <div class="item">
                    <div class="icon">
                      <img src="{% static 'assets/images/service-01.jpg' %}" alt="" style="max-width: 60px; border-radius: 50%;">
                    </div>
                    <h4>Go To Your Profile</h4>
                  </div>
                </div>
                <div class="col-lg-4">
                  <div class="item">
                    <div class="icon">
                      <img src="{% static 'assets/images/service-02.jpg' %}" alt="" style="max-width: 60px; border-radius: 50%;">
                    </div>
                    <h4>Live Stream Button</h4>
                  </div>
                </div>
                <div class="col-lg-4">
                  <div class="item">
                    <div class="icon">
                      <img src="{% static 'assets/images/service-03.jpg' %}" alt="" style="max-width: 60px; border-radius: 50%;">
                    </div>
                    <h4>You Are Live</h4>     
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="main-button">
                    
                    {% if request.user.is_authenticated %}
                      <a href="{% url 'accounts:profile' request.user.profile.slug %}">Go To Profile</a>
                    {% else %}
                      <a href="{% url 'accounts:login' %}">Go To Profile</a>
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- ***** Start Stream End ***** -->

          <!-- ***** Live Stream Start ***** -->
          <div class="live-stream">
            <div class="col-lg-12">
              <div class="heading-section">
                <h4><em>Most Popular</em> Live Stream</h4>
              </div>
            </div>
            <div class="row">
              {% for stream in streams %}
                
                {% if stream.status == True %}
                  <div class="col-lg-3 col-sm-6">
                    <div class="item">
                      <div class="thumb">
                        <img src="{{stream.image.url}}" alt="">
                        <div class="hover-effect">
                          <div class="content">
                            <div class="live">
                              <a href="#">Live</a>
                            </div>
                            <ul>
                              <li><a href="#"><i class="fa fa-eye"></i> {{stream.viewers.count}}</a></li>
                              <li><a href="#"><i class="fa fa-gamepad"></i> {{stream.type}}</a></li>
                            </ul>
                          </div>
                        </div>
                      </div>
                      <div class="down-content">
                        <div class="avatar">
                          <img src="{{stream.streamer.profile.image.url}}" alt="" style="max-width: 46px; border-radius: 50%; float: left;">
                        </div>
                        <span><i class="fa fa-check"></i> <a href="{% url 'accounts:profile' stream.streamer.profile.slug %}">{{stream.streamer}}</a></span>
                        <h4>{{stream.title}}</h4>
                      </div> 
                    </div>
                  </div>
                {% endif %}
                  
              {% endfor %}
              <div class="col-lg-12">
                <div class="main-button">
                  <a href="{% url 'streams:streams' %}">Discover All Streams</a>
                </div>
              </div>
            </div>
          </div>
          <!-- ***** Live Stream End ***** -->

{% endblock content %}

project/templates/pages/details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<!-- ***** Featured Start ***** -->
<div class="row">
  <div class="col-lg-12">
    <div class="feature-banner header-text">
      <div class="row">
        <div class="col-lg-4">
          <img src="{{game.mimage.url}}" alt="" style="border-radius: 23px;">
        </div>
        <div class="col-lg-8">
          <div class="thumb">
            <img src="{{game.mimage.url}}" alt="" style="border-radius: 23px;">
            <a href="https://www.youtube.com/watch?v=r1b03uKWk_M" target="_blank"><i class="fa fa-play"></i></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- ***** Featured End ***** -->

<!-- ***** Details Start ***** -->
<div class="game-details">
  <div class="row">
    <div class="col-lg-12">
      <h2>{{game.name}} Details</h2>
    </div>
    <div class="col-lg-12">
      <div class="content">
        <div class="row">
          <div class="col-lg-6">
            <div class="left-info">
              <div class="left">
                <h4>{{game.name}}</h4>
                <span>{{game.company}}</span>
              </div>
              <ul>
                <li><i class="fa fa-star"></i> {{game.rate}}</li>
                <li><i class="fa fa-download"></i> {{game.downloaders.count}}</li>
              </ul>
            </div>
          </div>
          <div class="col-lg-6">
            <div class="right-info">
              <ul>
                <li><i class="fa fa-star"></i> {{game.rate}}</li>
                <li><i class="fa fa-download"></i> {{game.downloaders.count}}</li>
                <li><i class="fa fa-server"></i> {{game.storage}}GB</li>
                <li><i class="fa fa-gamepad"></i> {{game.type}}</li>
              </ul>
            </div>
          </div>
          
          {% for image in game.images.all %}
            <div class="col-lg-4">
              <img src="{{image.image.url}}" alt="" style="border-radius: 23px; margin-bottom: 30px;">
            </div>
          {% endfor %}
            
          <div class="col-lg-12">
            <p>{{game.discription}}</p>
          </div>
          <div class="col-lg-12">
            
              
              {% if game in request.user.games.all %}
                <div class="main-border-button border-no-active">
                  <a href="#">Downloaded</a>
                </div>
              {% else %}
                <div class="main-border-button">
                  <a href="#">Download {{game.name}} Now!</a>
                </div>
              {% endif %}
            
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- ***** Details End ***** -->

<!-- ***** Other Start ***** -->
<div class="other-games">
  <div class="row">
    <div class="col-lg-12">
      <div class="heading-section">
        <h4><em>Other Related</em> Games</h4>
      </div>
    </div>
    
    {% for game in games %}
      <div class="col-lg-6">
        <div class="item">
          <img src="{{game.mimage.url}}" alt="" class="templatemo-item">
          <h4><a href="{% url 'games:details' game.slug %}">{{game.name}}</a></h4><span>{{game.company}}</span>
          <ul>
            <li><i class="fa fa-star"></i> {{game.rate}}</li>
            <li><i class="fa fa-download"></i> {{game.downloaders.count}}</li>
          </ul>
        </div>
      </div>
    {% endfor %}
  </div>
</div>
<!-- ***** Other End ***** -->
{% endblock content %}

project/templates/pages/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  

<!-- ***** Banner Start ***** -->
<div class="main-banner">
  <div class="row">
    <div class="col-lg-7">
      <div class="header-text">
        <h6>Welcome To Cyborg</h6>
        <h4><em>Browse</em> Our Popular Games Here</h4>
        <div class="main-button">
          <a href="{% url 'games:browse' %}">Browse Now</a>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- ***** Banner End ***** -->

<!-- ***** Most Popular Start ***** -->
<div class="most-popular">
  <div class="row">
    <div class="col-lg-12">
      <div class="heading-section">
        <h4><em>Most Popular</em> Right Now</h4>
      </div>
      <div class="row">
        {% for game in games|slice:"4" %}
          <div class="col-lg-3 col-sm-6">
            <div class="item">
              <img src="{{game.mimage.url}}" alt="">
              <h4><a href="{% url 'games:details' game.slug %}">{{game.name}}</a><br><span>{{game.company}}</span></h4>
              <ul>
                <li><i class="fa fa-star"></i>{{game.rate}}</li>
                <li><i class="fa fa-download"></i> {{game.downloaders.count}}</li>
              </ul>
            </div>
          </div>
        {% endfor %}
        <div class="col-lg-12">
          <div class="main-button">
            <a href="{% url 'games:browse' %}">Discover Popular</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- ***** Most Popular End ***** -->

<!-- ***** Gaming Library Start ***** -->
{% if request.user.is_authenticated %}
  <div class="gaming-library">
    <div class="col-lg-12">
      <div class="heading-section">
        <h4><em>Your Gaming</em> Library</h4>
      </div>
      
      {% for game in request.user.games.all %}
        <div class="item">
          <ul>
            <li><img src="{{game.mimage.url}}" alt="" class="templatemo-item"></li>
            <li><h4><a href="{% url 'games:details' game.slug %}">{{game.name}}</a></h4><span>{{game.company}}</span></li>
            <li><h4>Date Added</h4><span>{{game.data_added}}</span></li>
            <li><h4>Hours Played</h4><span>634 H 22 Mins</span></li>
            <li><h4>Currently</h4><span>Downloaded</span></li>
            <li><div class="main-border-button border-no-active"><a href="#">Donwloaded</a></div></li>
          </ul>
        </div>
      {% endfor %}
    </div>
    <div class="col-lg-12">
      <div class="main-button">
        <a href="{% url 'accounts:profile' request.user.profile.slug %}">Go To Profile</a>
      </div>
    </div>
  </div>
{% endif %}
<!-- ***** Gaming Library End ***** -->

{% endblock content %}

project/templates/pages/profile.html
{% extends 'base.html' %}
{% block content %}

<!-- ***** Banner Start ***** -->
<div class="row">
  <div class="col-lg-12">
    <div class="main-profile ">
      <div class="row">
        <div class="col-lg-4">
          <img src="{{profile.image.url}}" alt="" style="border-radius: 23px;">
        </div>
        <div class="col-lg-4 align-self-center">
          <div class="main-info header-text">
            
            {% if request.user %}
              <span>Online</span>
            {% else %}
              <span>Offline</span>
            {% endif %}
            <h4>{{profile.user.first_name}}</h4>
            <p>{{profile.bio}}</p>
            
            {% if profile.user == request.user %}
              <div class="main-border-button">
                <a href="#">Start Live Stream</a>
              </div>
            {% endif %}
          </div>
        </div>
        <div class="col-lg-4 align-self-center">
          <ul>
            <li>Games Downloaded <span>{{profile.user.games.count}}</span></li>
            <li>Friends Online <span>{{profile.friends.count}}</span></li>
            <li>Live Streams <span>{{profile.user.streams.count}}</span></li>
            <li>Clips <span>{{profile.user.clipper.count}}</span></li>
          </ul>
        </div>
      </div>
      
      {% if profile.user.clipper.count > 0 %}
      <div class="row">
        <div class="col-lg-12">
          <div class="clips">
            <div class="row">
              <div class="col-lg-12">
                <div class="heading-section">
                  {% if profile.user == request.user %}
                    <h4><em>Your Most Popular</em> Clips</h4>
                  {% else %}
                    <h4><em>His Most Popular</em> Clips</h4>
                  {% endif %}
                </div>
              </div>
              
              {% for clip in profile.user.clipper.all %}
                <div class="col-lg-3 col-sm-6">
                  <div class="item">
                    <div class="thumb">
                      <img src="{{clip.image}}" alt="" style="border-radius: 23px;">
                      <a href="https://www.youtube.com/watch?v=r1b03uKWk_M" target="_blank"><i class="fa fa-play"></i></a>
                    </div>
                    <div class="down-content">
                      <h4>{{clip.title}}</h4>
                      <span><i class="fa fa-eye"></i> {{clip.viewers.count}}</span>
                    </div>
                  </div>
                </div>
              {% endfor %}
              {% comment %} <div class="col-lg-12">
                <div class="main-button">
                  <a href="#">Load More Clips</a>
                </div>
              </div> {% endcomment %}
            </div>
          </div>
        </div>
      </div>
      {% endif %}
    </div>
  </div>
</div>
<!-- ***** Banner End ***** -->

<!-- ***** Gaming Library Start ***** -->
{% if profile.user == request.user %}
  <div class="gaming-library profile-library">
    <div class="col-lg-12">
      <div class="heading-section">
        <h4><em>Your Gaming</em> Library</h4>
      </div>
      
      {% for game in profile.user.games.all %}
        <div class="item">
          <ul>
            <li><img src="{{game.mimage.url}}" alt="" class="templatemo-item"></li>
            <li><h4><a href="{% url 'games:details' game.slug %}">{{game.name}}</a></h4><span>{{game.company}}</span></li>
            <li><h4>Date Added</h4><span>{{game.data_added}}</span></li>
            <li><h4>Hours Played</h4><span>634 H 22 Mins</span></li>
            <li><h4>Currently</h4><span>Downloaded</span></li>
            <li><div class="main-border-button border-no-active"><a href="#">Donwloaded</a></div></li>
          </ul>
        </div>	
      {% endfor %}

    </div>
  </div>
{% endif %}
<!-- ***** Gaming Library End ***** -->

{% endblock content %}

project/templates/pages/streams.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


        <!-- ***** Featured Games Start ***** -->
        <div class="row">
          <div class="col-lg-8">
            <div class="featured-games header-text">
              <div class="heading-section">
                <h4><em>Live</em> Streams</h4>
              </div>
              <div class="owl-features owl-carousel">
                
                {% for game in games %}
                  <div class="item">
                    <div class="thumb">
                      <img src="{{game.mimage.url}}" alt="">
                      <div class="hover-effect">
                        <h6>{{game.streams.count}} Streaming</h6>
                      </div>
                    </div>
                    <h4><a href="{% url 'games:details' game.slug %}">{{game.name}}</a><br><span>{{game.downloaders.count}} Downloads</span></h4>
                    <ul>
                      <li><i class="fa fa-star"></i> {{game.rate}}</li>
                      <li><i class="fa fa-download"></i> {{game.downloaders.count}}</li>
                    </ul>
                  </div>
                {% endfor %}
                  
              </div>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="top-streamers">
              <div class="heading-section">
                <h4><em>Top</em> Streamers</h4>
              </div>
              <ul>
                {% for streamer in streamers %}
                  {% if streamer.streams.count > 0 %}
                    <li>
                      <span>01</span>
                      <img src="{{streamer.profile.image.url}}" alt="" style="max-width: 46px; border-radius: 50%; margin-right: 15px;">
                      <h6><i class="fa fa-check"></i> <a href="{% url 'accounts:profile' streamer.profile.slug %}">{{streamer.username}}</a></h6>
                      <div class="main-button">
                        
                        <a href = "{% url 'accounts:addfriend' streamer %}">
                          <i class="fa-solid fa-user-plus"></i>
                        </a>
                      </div>
                    </li>
                  {% endif %}
                {% endfor %}
              </ul>
            </div>
          </div>
        </div>
        <!-- ***** Featured Games End ***** -->

        <!-- ***** Live Stream Start ***** -->
        <div class="live-stream">
          <div class="col-lg-12">
            <div class="heading-section">
              <h4><em>Most Popular</em> Live Stream</h4>
            </div>
          </div>
          <div class="row">
            
            {% for stream in streams %}
              {% if stream.status == True %}
                <div class="col-lg-3 col-sm-6">
                  <div class="item">
                    <div class="thumb">
                      <img src="{{stream.image.url}}" alt="">
                      <div class="hover-effect">
                        <div class="content">
                          <div class="live">
                            <a href="#">Live</a>
                          </div>
                          <ul>
                            <li><a href="#"><i class="fa fa-eye"></i> {{stream.viewers.count}}</a></li>
                            <li><a href="#"><i class="fa fa-gamepad"></i> {{stream.type}}</a></li>
                          </ul>
                        </div>
                      </div>
                    </div>
                    <div class="down-content">
                      <div class="avatar">
                        <img src="{{stream.streamer.profile.image.url}}" alt="" style="max-width: 46px; border-radius: 50%; float: left;">
                      </div>
                      <span><i class="fa fa-check"></i> <a href="{% url 'accounts:profile' stream.streamer.profile.slug %}">{{stream.streamer}}</a></span>
                      <h4>{{stream.title}}</h4>
                    </div> 
                  </div>
                </div>
              {% endif %}
            {% endfor %}
          </div>
        </div>
        <!-- ***** Live Stream End ***** -->


{% endblock content %}

project/templates/parts/footer.html
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright © 2036 <a href="#">Cyborg Gaming</a> Company. All rights reserved. 
            
                <br>Design: <a href="https://templatemo.com" target="_blank" title="free CSS templates">TemplateMo</a></p>
            </div>
        </div>
    </div>
</footer>

project/templates/parts/header.html
{% load static %}

<!-- ***** Header Area Start ***** -->
<header class="header-area header-sticky">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav class="main-nav">
                    <!-- ***** Logo Start ***** -->
                    <a href="{% url 'games:index' %}" class="logo">
                        <img src="{% static 'assets/images/logo.png' %}" alt="">
                    </a>
                    <!-- ***** Logo End ***** -->
                    <!-- ***** Search End ***** -->
                    <div class="search-input">
                        <form id="search" action="{% url 'games:search' %}">
                            <input type="text" placeholder="Type Something" id='searchText' name="searchKeyword" onkeypress="handle"/>
                            <i class="fa fa-search"></i>
                        </form>
                    </div>
                    <!-- ***** Search End ***** -->
                    <!-- ***** Menu Start ***** -->
                    <ul class="nav">
                        <li><a href="{% url 'games:index' %}">Home</a></li>

                        <li><a href="{% url 'games:browse' %}">Browse</a></li>

                        <li><a href="{% url 'streams:streams' %}">Streams</a></li>
                        
                        
                        {% if request.user.is_authenticated %}
                            <li><a href="{% url 'accounts:profile' request.user.profile.slug %}">Profile <img src="{{request.user.profile.image.url}}" alt=""></a></li>
                        {% else %}
                            <li><a href="{% url 'accounts:login' %}">Login</a></li>
                        {% endif %}
                    </ul>   
                    <a class='menu-trigger'>
                        <span>Menu</span>
                    </a>
                    <!-- ***** Menu End ***** -->
                </nav>
            </div>
        </div>
    </div>
</header>
<!-- ***** Header Area End ***** -->